apiVersion: apps/v1
kind: Deployment
metadata:
  name: fm-environments-auth-api-deployment
  labels:
    app: fm-environments-auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fm-environments-auth-api
  template:
    metadata:
      labels:
        app: fm-environments-auth-api
    spec:
      containers:
      - name: fm-environments-auth-api
        image: kuzyacat/fm-environments-auth-api
        ports:
        - containerPort: 3001
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postres-secret
              key: postgres-password 
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-url
---
apiVersion: v1
kind: Service
metadata:
  name: fm-environments-auth-service
spec:
  type: NodePort
  selector:
    app: fm-environments-auth
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30101
